### PR TITLE
Written Relevant Tests

### PR DESCRIPTION
**Pull request by SavvyHex**
I've created a main_test.go file with relevant tests and moved some structs to another file (models.go) as they are frequently reused

### CODE REVIEW

**Comment by SavvyHex** [comment]
since the /execute-command endpoint hasn't been created yet, the test_command_execution.go file is riddled with errors

**Comment by 0xIcarus** [comment]
@SavvyHex Are you still working on this?

**Comment by SavvyHex** [comment]
I've submitted a pull request with the tests for the execute command endpoint.

**Comment by 0xIcarus** [comment]
looks like tests are still failing-- could you check and revert?

**Comment by SavvyHex** [comment]
The tests work for everything except the execute command endpoint, which doesn't exist yet, so...

**Comment by 0xIcarus** [comment]
Just add a simple endpoint in `main.go` to give a 200 OK so that the tests will pass. Do not worry about the logic for the test suite

**Comment by SavvyHex** [comment]
Ahhh got it, just give me some time

**Comment by SavvyHex** [comment]
yeah, done

**Comment by 0xIcarus** [comment]
!bounty 250

**Pull request closed without merging**
